name: cron-apps

on:
  push:
    branches:    
      - main
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 每周日

jobs:
  generate:
    name: Generate on ${{ matrix.os }} with node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    permissions:
      contents: write
      # issues: write # 重写了 permissions，故而需要额外添加 contents 权限，不然 git clone 会失败
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: alexv587/app-cli
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Run install@shell
        run: |
          npm install
      - name: Run Generate All App Info
        uses: actions/github-script@v6
        with:
          script: |
            var execSync = require('child_process').execSync;
            var apps = [
              {
                name: "RDWords",
                bundles: {
                  android: "reverse.dictionary.wantwords.bravo.oxford.xinhua.english.chinese",
                  ios: undefined,
                },
              },
              {
                name: "PrismWalls",
                bundles: {
                  android: "hd.uhd.quality.wallpaper.pexels.walls.walpy.walli",
                  ios: undefined,
                },
              },
              {
                name: "VOLT Charging Play",
                bundles: {
                  android: "charging.animation.play.show.fun.pika.battery.flashing",
                  ios: undefined,
                },
              },
            ];
            apps.forEach(function (app) {
              console.log("app: " + app.name);
              if (app.bundles.android) {
                execSync("npm run dev -- gplay --appId " + app.bundles.android + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- gplay --country cn --lang zh --appId " + app.bundles.android + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- aso --store gplay --appId " + app.bundles.android + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- aso --store gplay --country cn --lang zh --appId " + app.bundles.android + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
              }
              if (app.bundles.ios) {
                execSync("npm run dev -- store --appId " + app.bundles.ios + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- store --country cn --lang zh --appId " + app.bundles.ios + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- aso --store itunes --appId " + app.bundles.ios + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
                execSync("npm run dev -- aso --store itunes --country cn --lang zh --appId " + app.bundles.ios + " --debug", { encoding: "utf-8", stdio: "inherit", shell: true });
              }
            });
      - name: Checkout Github Pages
        continue-on-error: true # 忽略 gh-pages 分支未创建
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Merge Github Pages
        run: |
          # 避免 gh-pages 分支未创建
          mkdir -p gh-pages
          # 计划任务无法准确描述月底
          if [ -d dist/gh-pages ]; then cp -r dist/gh-pages/. gh-pages/; fi
      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
          branch: gh-pages
